name = "EventStudies"
uuid = "a22a033a-3589-4878-889c-593115a581a1"
authors = ["xKDR Forum"]
version = "0.1.0"

[deps]
Bootstrap = "e28b5b4c-05e8-5b66-bc03-6f0c0a0a06e0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TSFrames = "9f90e835-9451-4aaa-bcb1-743a1b8d2f84"

[compat]
Bootstrap = "2"
DataFrames = "1"
GLM = "1.7, 1.8"
HypothesisTests = "0.10"
julia = "1"
